language: python
matrix:
    include:
        - os: linux
          sudo: required
          python: 3.7-dev

install:
    - pip install pyinstaller pep8
    - echo "__version__ = '$(git describe --tags --always)'" > steamgamestattracker/version.py
    - cat steamgamestattracker/version.py
    - pip install -r requirements.txt
    - pyinstaller steam_game_stat_tracker.py

script:
    - find . -name \*.py -exec pep8 --ignore=E501 {} \;

addons:
    artifacts:
        debug: true
        paths:
            - $(find . -type f | grep -e '/bin/' -e 'dist/steamgamestattracker$' | awk 1 ORS=':')
        target_paths: travis/$TRAVIS_OS_NAME/
