version: 0.0.{build}
shallow_clone: true
clone_depth: 1
build:
  verbosity: minimal

environment:
  matrix:
    # For Python versions available on Appveyor, see
    # https://www.appveyor.com/docs/windows-images-software/#python
    - PYTHON: "C:\\Python37"

install:
  # We need wheel installed to build wheels
  - "%PYTHON%\\python.exe -m pip install wheel"