version: 0.0.{build}
shallow_clone: true
clone_depth: 1

environment:
    matrix:
        - PYTHON: "C:\\Python37"
          ARCH: "32"

install:
    - "%PYTHON%\\python.exe --version"
    - "%PYTHON%\\Scripts\\pip install --no-warn-script-location pyinstaller"
    - ps: Set-Content "steamgamestattracker\\version.py" ( "__version__ = '{0}'" -f ( $env:APPVEYOR_BUILD_VERSION ) )
    - "%PYTHON%\\Scripts\\pip install --no-warn-script-location -r requirements.txt"

build:
  verbosity: normal

build_script:
    - "%PYTHON%\\Scripts\\pyinstaller steam_game_stat_tracker.py"

after_build:
  - ps: 7z a steam_game_stat_tracker-$env:APPVEYOR_BUILD_VERSION-windows.zip .\dist\steam_game_stat_tracker\*
  - ps: 7z a steam_game_stat_tracker-$env:APPVEYOR_BUILD_VERSION-windows.7z .\dist\steam_game_stat_tracker\*

artifacts:
    - path: "steam_game_stat_tracker-*-windows.zip"
    - path: "steam_game_stat_tracker-*-windows.7z"

deploy:
  - provider: GitHub
    release: steam_game_stat_tracker-v$(appveyor_build_version)
    auth_token:
      secure: 208TDvAq+KHsvan3IIpa1CyuzFxO7cw/0zMjSxogqBGbnkNUxQU6g6YUiekFAWRC
    artifact: "steam_game_stat_tracker-$(appveyor_build_version)-windows.zip"
    draft: true
    prerelease: false
    on:
      branch: master                 # release from master branch only

  - provider: GitHub
    release: steam_game_stat_tracker-v$(appveyor_build_version)
    auth_token:
      secure: 208TDvAq+KHsvan3IIpa1CyuzFxO7cw/0zMjSxogqBGbnkNUxQU6g6YUiekFAWRC
    artifact: "steam_game_stat_tracker-$(appveyor_build_version)-windows.7z"
    draft: true
    prerelease: false
    on:
      branch: master                 # release from master branch only

  - provider: GitHub
    release: steam_game_stat_tracker-v$(appveyor_build_version)
    auth_token:
      secure: 208TDvAq+KHsvan3IIpa1CyuzFxO7cw/0zMjSxogqBGbnkNUxQU6g6YUiekFAWRC
    artifact: "steam_game_stat_tracker-$(appveyor_build_version)-windows.zip"
    draft: false
    prerelease: true
    on:
      branch: master                 # release from master branch only
      APPVEYOR_REPO_TAG: true

  - provider: GitHub
    release: steam_game_stat_tracker-v$(appveyor_build_version)
    auth_token:
      secure: 208TDvAq+KHsvan3IIpa1CyuzFxO7cw/0zMjSxogqBGbnkNUxQU6g6YUiekFAWRC
    artifact: "steam_game_stat_tracker-$(appveyor_build_version)-windows.7z"
    draft: false
    prerelease: true
    on:
      branch: master                 # release from master branch only
      APPVEYOR_REPO_TAG: true